### ISSUE TITLE
Add ob/ob to C57BL/6J in figure

### ISSUE THREAD

**Issue by dmgatti** [smcclatchy/qtl-mapping#5]
In fig/intercross.png, which is used in intro-data-set.Rmd, add ob/ob to C57BL/6J. I think that they have the ob mutation in both strains, although it's unclear from the text and their other papers. I could try e-mailing Mark Keller to clarify.

**Comment by smcclatchy** [comment]
For the sake of accuracy would you mind asking him? I wouldn't want to misrepresent what they did.
